config/routes.rb
Rails.application.routes.draw do
	mount Ckeditor::Engine => '/ckeditor'
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)
	root 'tovar#index'
	get 'news' =>  'news#index'
	get 'news/:url' =>  'news#show', as: 'news_show_url'
	get 'comments/new' =>  'comments#new'
	get 'comments' =>  'comments#index'
	post "comments" => "comments#create"
	get 'tovar/:url' =>  'tovar#show', as: 'tovar_url'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	
devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/architecture_img.rb
class ArchitectureImg < ActiveRecord::Base
	belongs_to :tovar
	has_attached_file :arhitect_img, :styles => {:thumb => "800x504>", admin: "50x50>" }, default_url: "missing.png"
	validates_attachment_content_type :arhitect_img, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :name, :email,  :comment, presence: true
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  has_many :filter_attributes
end

app/models/filter_attribute.rb
class FilterAttribute < ActiveRecord::Base
   belongs_to :filter
end

app/models/news.rb
class News < ActiveRecord::Base
	validates :title, :keywords,  :description, :name, :url, presence: true
	validates :url, uniqueness: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
   has_and_belongs_to_many :tovar
end

app/models/tovar.rb
class Tovar < ActiveRecord::Base
  has_many :architecture_img
  accepts_nested_attributes_for :architecture_img, allow_destroy: true

  has_and_belongs_to_many :tag
  accepts_nested_attributes_for :tag, allow_destroy: true

  has_and_belongs_to_many :filter
  accepts_nested_attributes_for :tag, allow_destroy: true

  validates :name, :url, :image, presence: true
  validates :url, uniqueness: true
  validates_format_of :url, :with => /\A[А-Яа-яA-Za-z0-9\-\_]+\Z/

  has_attached_file :image, :styles => {:thumb => "1000x1000>", admin: "50x50>" }, default_url: "missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  attr_writer :remove_image
  before_validation { self.image.clear if self.remove_image == '1' }

  def remove_image
    @remove_image || false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@сomments = Comment.where(moderate: true)
	end
	def new
		@сomment = Comment.new
	end
	def create
		@сomment = Comment.new(comment_params)
		if @сomment.save
			redirect_to comments_new_path, notice: "Коментарій добавлено!"
		else
			flash.now.alert = "Помилка!"
			render :new
		end
	end
	private
	def comment_params
		params.require(:comment).permit(:name, :email, :comment, :moderate)
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def index
		@news = News.all.paginate(:page => params[:page], :per_page => 2)
	end
	def show
		@news = News.find_by_url(params[:url])
	end
end

app/controllers/tovar_controller.rb
class TovarController < ApplicationController
	def index
		@tovars = Tovar.all.where(position: true).order(position: :asc)
		@filter = Filter.all
	end
	def show
		@tovars = Tovar.find_by_url(params[:url])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tovar_helper.rb
module TovarHelper
end

app/views/comments/index.html.erb
<h1>Це загальна сторінка, для виводу усіх товарів, юзери...</h1><br/>
<% @сomments.each do |i| %>
    <div class="tovar ">                                    
		<p class="name_tovar"><%= i.name %></p>                         
		<p class="name_tovar"><%= i.email %></p>
		<p class="name_tovar"><%= i.comment %></p>
    </div>                   
<% end %>

app/views/comments/new.html.erb
<h1>Create new</h1>

<%= form_for @сomment do |f| %>
	<p>Имя: <br/><%= f.text_field :name %></p>
	<p>Майл: <br/><%= f.text_field :email %></p>
	<p>Коментарий: <br/><%= f.text_field :comment %></p>
	<p><%= f.submit "Добавить" %></p>
<% end %>

app/views/comments/show.html.erb
<h1>на шов ти задаєш конкретну айдішку і він виводить конкретну запись</h1>

app/views/news/index.html.erb
<div class="catalog_index clearfix">
    <hr class="liniya">
    <div class="tovaru">
        <div class="tovar ">                           
            <div class="price">
                <% @news.each do |i| %>
                    <p><%= link_to  news_show_url_path(i.url), :class => "mails" do %></p><br/>
                        <p class="cena_stara"><%= i.name %></p>
                    <% end %>
                <% end %>
                    <%= will_paginate @news, :container => false %>
            </div>
        </div>
    </div>
</div>

app/views/news/show.html.erb
<div class="catalog_index clearfix">
    <hr class="liniya">
    <div class="tovaru">
        <div class="tovar ">                           
            <div class="price">
				<h1><%= @news.name %></h1><br/>
				<ul>			   
					<li><p class="phone_header"> Name: </p><span class="mails"><%= @news.name%></span></li><br/>
					<li><p class="phone_header">Description: </p><span class="mails"><%= @news.description %></span></li><br/>
					<li><p class="phone_header">Text: </p><span class="mails"><%= @news.text %></span></li><br/>
					<li><p class="phone_header">Title: </p><span class="mails"><%= @news.title %></span></li><br/>
					<li><p class="phone_header">Keywords: </p><span class="mails"><%= @news.keywords  %></span></li><br/>
				</ul>
            </div>
        </div>
    </div>
</div>
<h1><span class="phone_header"> Title - </span><span class="mails"> технически называется титровальных элементов-определить название документа. Название метки часто используются на страницах результатов поисковой машины (поисковой выдачи), чтобы отобразить предварительный просмотр фрагментов для данной страницы, и имеют важное значение как для SEO и социального обмена.</span> </h1><br/>
<h1><span class="phone_header">Keywords - </span><span class="mails"> Ключевое слово исследований является одним из наиболее важных, ценных и высокой доходности деятельности в области поискового маркетинга. Рейтинг для правильных ключевых слов может сделать перерыв или ваш сайт. В исследовании спроса ключевое слово вашего рынка, вы можете не только узнать, какие термины и фразы, чтобы предназначаться с SEO, но также узнать больше о ваших клиентов в целом.</span></h1><br/>
<h1><span class="phone_header"> Description - </span><span class="mails"> Мета-тег описания в HTML является фрагмент 160 символов, используемый для обобщения содержания веб-страницы. Поисковые системы иногда используют эти фрагменты в результатах поиска, чтобы посетители знают, что страница о прежде чем они щелкните по нему.</span></h1><br/>

app/views/tovar/index.html.erb
<div class="wrapper ">
    <div class="fix_footer">
        <div class="besedka clearfix">
            <div class="item pull-left">
                <%= link_to root_url do %>
                    <img src="/assets/img.png" alt="">
                    <div class="desc_item">Скидка 10% на все беседки</div>
                <% end %>
            </div>
            <div class="item pull-left">
                <%= link_to root_url do %>
                    <img src="/assets/img.png" alt="">
                    <div class="desc_item">Скидка 10% на все беседки</div>
                <% end %>
            </div>
        </div> 
        <div class="content">
            <h2>О компании</h2>
            <hr class="liniya">
            <p class="text">
                <span>Пергола</span>  – очаровательный представитель семейства решетчатых среди арок, трельяжей, беседок, берсо и навесов.
                Отличительные черты пергол – конструкция малой архитектурной формы создается в виде ажурного коридора из вертикальных опор,
                горизонтальных и дуговых элементов, которые укажут путь в глубину сада и порадуют глаз яркими красками флористики.
            </p>
            <p class="text"><span> Классическая пергола</span> – это конструкция из нескольких арок, которые составлены друг с другом и соединены решетчатым 
            перекрытием.Благодаря изящной форме сооружений, обычная дорожка (см. как сделать садовую дорожку своими руками) превращается в стихию, 
            которая приглашает совершить увлекательную прогулку в глубину сада.
            Первые перголы Римской Империи служили для поддержки виноградной лозы и не отличались разнообразием. 
            Современный ассортимент ажурных коридоров – основной элемент ландшафтного дизайна, который отличается многообразием 
            конструктивных решений и вариантов декора.
            </p>
        </div>
        <div class="catalog_index clearfix">
            <h2>Каталог беседок</h2>
            <hr class="liniya">
            <% @filter.each do |filter| %>
                <% filter.filter_attributes.each do |item| %>
                    <p class="phone_header"><%= filter.name %></p>  
                    <%= check_box_tag "product[filter_ids][]" %>
                    <%= item.name %><br/>
                <% end %>
            <% end %>
            <% @tovars.each do |i| %>
                <div class="tovaru">             
                    <div class="tovar ">                        
                        <%= link_to tovar_url_path(i.url) do %>
                            <p class="name_tovar"><%= i.name %></p>
                            <%= image_tag i.image.url %>                            
                        <% end %>
                        <div class="price">
                            <p class="cena pull-left">Цена:</p>
                            <div class="price_tovara pull-left">
                                <p class="cena_stara"><%= i.price %></p>
                                <p class="cena_nova"><%= i.reprice %></p>
                            </div>
                            <%= link_to root_url, class:"korzuna" do %><% end %>
                        </div>                        
                    </div>    
                </div>
            <% end %>
            <%= link_to "Все товары", "#", class:"link_other pull-right" %>
        </div>
    </div>
</div>

app/views/tovar/show.html.erb
<div class="wrapper">
    <div class="bredkrams">
        <ul>
            <li><%= link_to root_url do %>Главная<%end%></a><span>/</span></li>
            <li><%= link_to root_url do %>Беседки<%end%></a><span>/</span></li>
            <li><%= @tovars.name %></li>
        </ul>
    </div>
    <div class="content_cart clearfix fix_footer">
        <div class="slider">
            <div id="slider" class="flexslider">
                <ul class="slides">
                    <% @tovars.architecture_img.each do |i| %>
                        <li>
                            <%= image_tag i.arhitect_img.url%>
                        </li>
                    <%end%>
                </ul>
            </div>
            <div id="carousel" class="flexslider">
                <ul class="slides">
                    <% @tovars.architecture_img.each do |i| %>
                        <li>    
                            <%= image_tag i.arhitect_img.url%>    
                        </li>
                    <%end%>
                </ul>
            </div>
        </div>
        <div class="desc_cart pull-left">
            <p class="name_cart">Технические характеристики</p>
            <div class="harakteristik">
                <div class="item_cart">
                    <span>Размеры:</span><span><%= @tovars.title %></span>
                </div>
                <div class="item_cart">
                    <span>Срок изготовления:</span><span><%= @tovars.text %></span>
                </div>
                <div class="price">
                    <p class="cena pull-left">Стоимость:</p>
                    <div class="price_tovara pull-left">
                        <p class="cena_stara zacherk"><%=@tovars.price%></p>
                        <p class="cena_nova"><%=@tovars.reprice%></p>
                    </div>
                </div>                               
                <span class="pull-left">Описание:</span>
                <div class="description_cart">
                    <p>
                        <%= @tovars.desc %>
                    </p> 
                </div>
                <a class="zakaz" href="#">Заказать изделие</a>                   
            </div>   
        </div>      
    </div>
</div>